<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    use WithoutModelEvents;

    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        $this->call(UserSeeder::class);

        $categories = collect(['Alcohol', 'Beer', 'Soft Drink', 'Cigarettes', 'Cheroots', 'Snacks', 'Other'])->mapWithKeys(fn (string $name) => [$name => Category::create(['name' => $name, 'slug' => str($name)->slug()])]);

        $products = [
            [
                'id' => 1,
                'category_id' => 4,
                'name' => 'Glan Master - အဝါ',
                'sku' => 'GM-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 2,
                'category_id' => 4,
                'name' => 'Glan Master - အနီ',
                'sku' => 'GM-002',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 3,
                'category_id' => 4,
                'name' => 'Glan Master - အပြာ',
                'sku' => 'GM-003',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 4,
                'category_id' => 4,
                'name' => 'Royal Club - အစိမ်း',
                'sku' => 'RC-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 5,
                'category_id' => 4,
                'name' => 'Royal Club - အပြာ',
                'sku' => 'RC-002',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 6,
                'category_id' => 4,
                'name' => 'Royal Club - အဝါ',
                'sku' => 'RC-003',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 7,
                'category_id' => 4,
                'name' => "MacArthur\'s - Whiskey",
                'sku' => 'MA-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 8,
                'category_id' => 4,
                'name' => 'Grand Royal - Double Gold',
                'sku' => 'GR-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 9,
                'category_id' => 4,
                'name' => 'Grand Royal - Sherry Cask',
                'sku' => 'GR-002',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 10,
                'category_id' => 4,
                'name' => 'Grand Royal - Shwe',
                'sku' => 'GR-003',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 11,
                'category_id' => 4,
                'name' => 'Grand Royal - Signature Blue',
                'sku' => 'GR-004',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 12,
                'category_id' => 4,
                'name' => 'Grand Royal - Smooth',
                'sku' => 'GR-005',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 13,
                'category_id' => 4,
                'name' => 'Empire - Rum',
                'sku' => 'EM-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 14,
                'category_id' => 4,
                'name' => 'Grand Royal - Black',
                'sku' => 'GR-006',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 15,
                'category_id' => 4,
                'name' => 'Brother - Smooth',
                'sku' => 'BR-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 16,
                'category_id' => 4,
                'name' => 'Mandalay - Rum Sherry',
                'sku' => 'MD-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 17,
                'category_id' => 4,
                'name' => 'Mandalay - 3 Year Export',
                'sku' => 'MD-002',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 18,
                'category_id' => 4,
                'name' => 'Mandalay - Coffee Rum',
                'sku' => 'MD-003',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 19,
                'category_id' => 4,
                'name' => 'Mandalay - White Rum',
                'sku' => 'MD-004',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 20,
                'category_id' => 4,
                'name' => 'Mandalay - Rum',
                'sku' => 'MD-005',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 21,
                'category_id' => 4,
                'name' => 'Mandalay - Rum Gold',
                'sku' => 'MD-007',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 22,
                'category_id' => 4,
                'name' => 'Myanmar - Rum Celebration',
                'sku' => 'MY-002',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 23,
                'category_id' => 4,
                'name' => 'Myanmar - Dry Gin',
                'sku' => 'MY-003',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 24,
                'category_id' => 4,
                'name' => 'Army - Rum',
                'sku' => 'AR-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 25,
                'category_id' => 4,
                'name' => 'Dagon - Rum',
                'sku' => 'DG-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 26,
                'category_id' => 4,
                'name' => 'Johnnie Walker - Blue Label',
                'sku' => 'JW-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 27,
                'category_id' => 4,
                'name' => 'Johnnie Walker - Double Black',
                'sku' => 'JW-002',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 28,
                'category_id' => 4,
                'name' => 'Johnnie Walker - Black Label',
                'sku' => 'JW-003',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 29,
                'category_id' => 4,
                'name' => 'Johnnie Walker - Red Label',
                'sku' => 'JW-004',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 30,
                'category_id' => 4,
                'name' => 'Chivas Regal - 12 Year',
                'sku' => 'CR-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 31,
                'category_id' => 4,
                'name' => 'Black Icon',
                'sku' => 'BI-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 32,
                'category_id' => 4,
                'name' => 'Dunfife - အပြာ',
                'sku' => 'DF-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 33,
                'category_id' => 4,
                'name' => 'Dunfife - အနီ',
                'sku' => 'DF-002',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 34,
                'category_id' => 4,
                'name' => 'Jägermeister',
                'sku' => 'JM-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 35,
                'category_id' => 4,
                'name' => 'ခေါင်ရည်ဘုရင် ၂ဆ',
                'sku' => 'KH-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 36,
                'category_id' => 4,
                'name' => 'ကိုးတောင်ကျား',
                'sku' => 'KT-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 37,
                'category_id' => 4,
                'name' => 'စစ်မြင်း',
                'sku' => 'SM-003',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 38,
                'category_id' => 3,
                'name' => "Sir Edward\'s - Smoky",
                'sku' => 'SE-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 39,
                'category_id' => 3,
                'name' => "Sir Edward\'s - Finest",
                'sku' => 'SE-002',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 40,
                'category_id' => 3,
                'name' => "Sir Edward\'s - Beer Reserve",
                'sku' => 'SE-003',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 41,
                'category_id' => 3,
                'name' => 'Keen - Beer',
                'sku' => 'KN-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 42,
                'category_id' => 3,
                'name' => 'Myanmar - Beer',
                'sku' => 'MY-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 43,
                'category_id' => 3,
                'name' => 'Black Shield - Beer',
                'sku' => 'BS-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 44,
                'category_id' => 3,
                'name' => 'Andaman Gold - Beer',
                'sku' => 'AG-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 45,
                'category_id' => 3,
                'name' => 'Chang - Beer',
                'sku' => 'CH-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 46,
                'category_id' => 3,
                'name' => 'Dagon - Beer',
                'sku' => 'DG-002',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 47,
                'category_id' => 3,
                'name' => 'Army - Beer',
                'sku' => 'AR-002',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 48,
                'category_id' => 3,
                'name' => 'Tuborg - Beer',
                'sku' => 'TB-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 49,
                'category_id' => 3,
                'name' => 'Carlsberg - Beer',
                'sku' => 'CB-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 50,
                'category_id' => 3,
                'name' => 'Yoma - Beer',
                'sku' => 'YM-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 51,
                'category_id' => 3,
                'name' => 'Black Eagle - Beer',
                'sku' => 'BE-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 52,
                'category_id' => 3,
                'name' => 'Tapper - Beer',
                'sku' => 'TP-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 53,
                'category_id' => 3,
                'name' => 'Dagon - Super Beer',
                'sku' => 'DG-003',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 54,
                'category_id' => 3,
                'name' => 'Yagon - Beer',
                'sku' => 'YG-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 55,
                'category_id' => 3,
                'name' => 'Mandalay - Beer',
                'sku' => 'MD-006',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 56,
                'category_id' => 3,
                'name' => 'Budweiser - Beer',
                'sku' => 'BW-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 57,
                'category_id' => 3,
                'name' => 'Corona - Beer',
                'sku' => 'CO-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 58,
                'category_id' => 3,
                'name' => 'Singha - Beer',
                'sku' => 'SG-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 59,
                'category_id' => 3,
                'name' => 'Leo - Beer',
                'sku' => 'LO-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 60,
                'category_id' => 3,
                'name' => 'Heineken - Beer',
                'sku' => 'HN-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 61,
                'category_id' => 3,
                'name' => 'ABC - Beer',
                'sku' => 'AB-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 62,
                'category_id' => 3,
                'name' => 'Tiger - Beer',
                'sku' => 'TG-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 63,
                'category_id' => 3,
                'name' => 'Tiger - Crystal',
                'sku' => 'TG-002',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 64,
                'category_id' => 3,
                'name' => 'Tiger - Super',
                'sku' => 'TG-003',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 65,
                'category_id' => 3,
                'name' => 'Tiger - Soju',
                'sku' => 'TG-004',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 66,
                'category_id' => 3,
                'name' => 'Bavaria - Beer',
                'sku' => 'BV-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 67,
                'category_id' => 3,
                'name' => 'R7 - အပြာ',
                'sku' => 'R7-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 68,
                'category_id' => 3,
                'name' => 'R7 - အနီ',
                'sku' => 'R7-002',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 69,
                'category_id' => 3,
                'name' => 'Bawdar - Beer',
                'sku' => 'BW-002',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 70,
                'category_id' => 6,
                'name' => 'Bora - Soju',
                'sku' => 'BO-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 71,
                'category_id' => 6,
                'name' => 'Joei - Soju',
                'sku' => 'JE-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 72,
                'category_id' => 6,
                'name' => 'Geonbae - Soju',
                'sku' => 'GB-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 73,
                'category_id' => 6,
                'name' => 'Chingu - Soju',
                'sku' => 'CG-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 74,
                'category_id' => 7,
                'name' => 'Fullmoon - Wine',
                'sku' => 'FM-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 75,
                'category_id' => 7,
                'name' => 'MayMyoWine - Wine',
                'sku' => 'MW-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 76,
                'category_id' => 5,
                'name' => 'A1 - Drink',
                'sku' => 'A1-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 77,
                'category_id' => 5,
                'name' => 'Blink - Energy Drink',
                'sku' => 'BL-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 78,
                'category_id' => 5,
                'name' => 'RRB - Energy Drink',
                'sku' => 'RRB-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 79,
                'category_id' => 5,
                'name' => 'Pop - Soda',
                'sku' => 'PP-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 80,
                'category_id' => 5,
                'name' => 'Dagon - Soda',
                'sku' => 'DG-004',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 81,
                'category_id' => 5,
                'name' => 'Vitamilk - Soy Milk',
                'sku' => 'VM-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 82,
                'category_id' => 5,
                'name' => 'Enervit - Energy Drink',
                'sku' => 'EV-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 83,
                'category_id' => 5,
                'name' => 'Color - Cola',
                'sku' => 'CL-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 84,
                'category_id' => 5,
                'name' => 'Honey Gold - Drink',
                'sku' => 'HG-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 85,
                'category_id' => 5,
                'name' => 'Sunkist - Soft Drink',
                'sku' => 'SK-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 86,
                'category_id' => 5,
                'name' => 'Mirinda - Soft Drink',
                'sku' => 'MR-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 87,
                'category_id' => 5,
                'name' => 'M-150 - Energy Drink',
                'sku' => 'M1-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 88,
                'category_id' => 5,
                'name' => 'Carabao - Energy Drink',
                'sku' => 'CRB-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 89,
                'category_id' => 5,
                'name' => 'Fire Dragon - Energy Drink',
                'sku' => 'FD-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 90,
                'category_id' => 5,
                'name' => 'Speed - Energy Drink',
                'sku' => 'SP-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 91,
                'category_id' => 5,
                'name' => 'Lipo - Energy Drink',
                'sku' => 'LP-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 92,
                'category_id' => 5,
                'name' => 'C-Vitt - Vitamin Drink',
                'sku' => 'CV-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 93,
                'category_id' => 5,
                'name' => 'Shark - Energy Drink',
                'sku' => 'SH-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 94,
                'category_id' => 5,
                'name' => 'Lucky Day - Coffee',
                'sku' => 'LD-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 95,
                'category_id' => 5,
                'name' => 'UFC - Drink',
                'sku' => 'UF-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 96,
                'category_id' => 5,
                'name' => 'Sunday - Drink',
                'sku' => 'SD-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 97,
                'category_id' => 5,
                'name' => 'Lactasoy - Soy Milk',
                'sku' => 'LS-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 98,
                'category_id' => 5,
                'name' => 'Milo - Chocolate Malt',
                'sku' => 'ML-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 99,
                'category_id' => 5,
                'name' => 'Ovaltine - Chocolate Malt',
                'sku' => 'OV-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 100,
                'category_id' => 5,
                'name' => 'Vita - Drink',
                'sku' => 'VT-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 101,
                'category_id' => 5,
                'name' => 'Yoko - Drink',
                'sku' => 'YK-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 102,
                'category_id' => 5,
                'name' => 'Max Plus - Drink',
                'sku' => 'MX-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 103,
                'category_id' => 5,
                'name' => 'V Cola - Cola',
                'sku' => 'VC-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 104,
                'category_id' => 5,
                'name' => 'D-POP - Drink',
                'sku' => 'DP-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 105,
                'category_id' => 5,
                'name' => 'Alpine - Drink',
                'sku' => 'AL-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 106,
                'category_id' => 5,
                'name' => 'Hikari - Drink',
                'sku' => 'HK-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 107,
                'category_id' => 5,
                'name' => 'Royal-D - Drink',
                'sku' => 'RD-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 108,
                'category_id' => 5,
                'name' => 'Regen-D - Drink',
                'sku' => 'RG-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 109,
                'category_id' => 5,
                'name' => 'Pepsi - Cola',
                'sku' => 'PE-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 110,
                'category_id' => 5,
                'name' => 'Sting - Energy Drink',
                'sku' => 'ST-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 111,
                'category_id' => 5,
                'name' => 'Blue Mountain - Drink',
                'sku' => 'BM-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 112,
                'category_id' => 5,
                'name' => 'Asia Delight - Drink',
                'sku' => 'AD-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 113,
                'category_id' => 5,
                'name' => 'Asia - ပင်မည့်',
                'sku' => 'AS-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 114,
                'category_id' => 5,
                'name' => 'Asia - လိုင်ချီး',
                'sku' => 'AS-002',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 115,
                'category_id' => 5,
                'name' => 'Yoshi - Drink',
                'sku' => 'YS-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 116,
                'category_id' => 5,
                'name' => 'သူဌေးမင်း',
                'sku' => 'STM-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 117,
                'category_id' => 5,
                'name' => 'Hello အရေခဲချောင်း',
                'sku' => 'HE-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 118,
                'category_id' => 5,
                'name' => 'ဝါးဟားဟား',
                'sku' => 'WH-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 119,
                'category_id' => 5,
                'name' => 'မန်းရှယ်',
                'sku' => 'MS-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 120,
                'category_id' => 5,
                'name' => 'မန်းမန်ကျည်း',
                'sku' => 'MM-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 121,
                'category_id' => 5,
                'name' => 'ဂျော်ကီ',
                'sku' => 'JK-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 122,
                'category_id' => 5,
                'name' => 'ဇေ',
                'sku' => 'ZE-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 123,
                'category_id' => 5,
                'name' => 'Sandar Aung - Drink',
                'sku' => 'SA-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 124,
                'category_id' => 8,
                'name' => 'Jasper - Water',
                'sku' => 'JP-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 125,
                'category_id' => 8,
                'name' => 'Life - Water',
                'sku' => 'LF-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 126,
                'category_id' => 10,
                'name' => 'My Chip - Chips',
                'sku' => 'MC-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 127,
                'category_id' => 10,
                'name' => 'Oshi - Snack',
                'sku' => 'OS-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 128,
                'category_id' => 10,
                'name' => '3+2 - Biscuit',
                'sku' => 'TK-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 129,
                'category_id' => 10,
                'name' => '၂၀၀ တန်',
                'sku' => 'PT-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 130,
                'category_id' => 10,
                'name' => '၃၀၀ တန်',
                'sku' => 'PT-002',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 131,
                'category_id' => 10,
                'name' => '၆၀၀ တန်',
                'sku' => 'PT-003',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 132,
                'category_id' => 10,
                'name' => '၇၀၀ တန်',
                'sku' => 'PT-004',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 133,
                'category_id' => 10,
                'name' => '၈၀၀ တန်',
                'sku' => 'PT-005',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 134,
                'category_id' => 10,
                'name' => '၁၀၀၀ တန်',
                'sku' => 'PT-006',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 08:12:07',
            ],
            [
                'id' => 135,
                'category_id' => 10,
                'name' => '၁၂၀၀ တန်',
                'sku' => 'PT-007',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 136,
                'category_id' => 10,
                'name' => '၁၅၀၀ တန်',
                'sku' => 'PT-008',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 137,
                'category_id' => 9,
                'name' => 'ယိုးဒယား မျက်လုံး',
                'sku' => 'ND-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 138,
                'category_id' => 9,
                'name' => 'Jumbo - Noodle',
                'sku' => 'JB-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 139,
                'category_id' => 9,
                'name' => 'X-cite - Noodle',
                'sku' => 'XC-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 140,
                'category_id' => 9,
                'name' => 'OMG - Noodle',
                'sku' => 'OG-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 141,
                'category_id' => 9,
                'name' => 'MAMA - Noodle',
                'sku' => 'MZ-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 142,
                'category_id' => 9,
                'name' => 'Yum Yum - Noodle',
                'sku' => 'YY-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 143,
                'category_id' => 9,
                'name' => 'XOXO - Noodle',
                'sku' => 'XX-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 144,
                'category_id' => 9,
                'name' => 'ယိုးဒယား ကြာဇံ',
                'sku' => 'ND-002',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 145,
                'category_id' => 9,
                'name' => 'Shin Shin - ကြာဇံ',
                'sku' => 'SS-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 146,
                'category_id' => 9,
                'name' => 'Ultra - Volcano',
                'sku' => 'UV-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 147,
                'category_id' => 2,
                'name' => 'Mevius - Sky Blue',
                'sku' => 'MV-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 148,
                'category_id' => 2,
                'name' => 'Winston - Cigarettes',
                'sku' => 'WS-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 149,
                'category_id' => 2,
                'name' => 'Lord - Cigarettes',
                'sku' => 'LR-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 150,
                'category_id' => 2,
                'name' => 'Dunhill - Red',
                'sku' => 'DH-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 151,
                'category_id' => 2,
                'name' => 'Black Devil - Cigarettes',
                'sku' => 'BD-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 152,
                'category_id' => 2,
                'name' => 'Black Fox - Cigarettes',
                'sku' => 'BF-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 153,
                'category_id' => 2,
                'name' => 'Red Ruby - Cigarettes',
                'sku' => 'RU-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 154,
                'category_id' => 2,
                'name' => 'Premium Gold - Cigarettes',
                'sku' => 'PG-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 155,
                'category_id' => 2,
                'name' => 'Red and Blue - Cigarettes',
                'sku' => 'RB-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 156,
                'category_id' => 2,
                'name' => 'Oris - Cigarettes',
                'sku' => 'OR-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 157,
                'category_id' => 2,
                'name' => 'Capital - Cigarettes',
                'sku' => 'CP-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 158,
                'category_id' => 2,
                'name' => 'O3 - Cigarettes',
                'sku' => 'O3-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 159,
                'category_id' => 2,
                'name' => 'Napoli - Cigarettes',
                'sku' => 'NP-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 160,
                'category_id' => 1,
                'name' => 'ကြယ်နီ',
                'sku' => 'KS-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 161,
                'category_id' => 1,
                'name' => 'လွင့်',
                'sku' => 'LW-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 162,
                'category_id' => 1,
                'name' => 'ရွှေဘားမား',
                'sku' => 'SM-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 163,
                'category_id' => 1,
                'name' => 'စကားဝါ',
                'sku' => 'SC-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 164,
                'category_id' => 1,
                'name' => 'မယ်ခွေ Strong',
                'sku' => 'MK-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 165,
                'category_id' => 1,
                'name' => 'မယ်ခွေ Smooth',
                'sku' => 'MK-002',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 166,
                'category_id' => 1,
                'name' => 'ရွှေမန်းသူ',
                'sku' => 'SM-002',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 167,
                'category_id' => 11,
                'name' => 'Tissue',
                'sku' => 'TS-001',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 07:50:38',
                'updated_at' => '2026-08-14 07:50:38',
            ],
            [
                'id' => 168,
                'category_id' => 10,
                'name' => 'လေးကျော်',
                'sku' => '-0168',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 08:14:40',
                'updated_at' => '2026-08-14 08:14:40',
            ],
            [
                'id' => 169,
                'category_id' => 10,
                'name' => 'အပျိုကြီး',
                'sku' => '-0169',
                'price_mode' => 'standard',
                'is_active' => true,
                'deleted_at' => null,
                'created_at' => '2026-08-14 08:16:14',
                'updated_at' => '2026-08-14 08:16:14',
            ],
        ];

        $categoryMap = [
            1 => $categories['Cheroots'],
            2 => $categories['Cigarettes'],
            3 => $categories['Beer'],
            4 => $categories['Alcohol'],
            5 => $categories['Soft Drink'],
            6 => $categories['Alcohol'],
            7 => $categories['Alcohol'],
            8 => $categories['Soft Drink'],
            9 => $categories['Snacks'],
            10 => $categories['Snacks'],
            11 => $categories['Other'],
        ];

        foreach ($products as $productData) {
            $categoryName = $categoryMap[$productData['category_id']]->name;
            $isBeer = $categoryName === 'Beer';
            $isCigarette = $categoryName === 'Cigarettes';
            $isCheroot = $categoryName === 'Cheroots';
            $isSoftDrink = $categoryName === 'Soft Drink';
            $isAlcohol = $categoryName === 'Alcohol';
            $isTobacco = $isCigarette || $isCheroot;
            $priceMode = $isTobacco ? 'single_package_carton' : 'single_package';
            $baseUnit = $isAlcohol || $isBeer || $isSoftDrink ? 'Bottle' : ($isTobacco ? 'Stick' : 'Piece');
            if ($isAlcohol) {
                $alcoholSizes = [
                    ['label' => '1L', 'purchase_price' => 10000, 'selling_price' => 12000],
                    ['label' => '750ML', 'purchase_price' => 8000, 'selling_price' => 10000],
                    ['label' => '350ML', 'purchase_price' => 4500, 'selling_price' => 6000],
                    ['label' => '50ML', 'purchase_price' => 1000, 'selling_price' => 1500],
                ];
                $units = collect($alcoholSizes)->flatMap(fn (array $size): array => [
                    ['name' => $size['label'].' Package', 'conversion' => 12, 'purchase_price' => $size['purchase_price'] * 12, 'selling_price' => $size['selling_price'] * 12, 'package_price' => $size['selling_price'] * 12, 'single_unit_price' => $size['selling_price']],
                ])->all();
            } elseif ($isBeer) {
                $beerFormats = [
                    ['name' => 'Big Bottle', 'purchase_price' => 1500, 'selling_price' => 2000],
                    ['name' => 'Small Bottle', 'purchase_price' => 1300, 'selling_price' => 1800],
                    ['name' => 'Long Can', 'purchase_price' => 1700, 'selling_price' => 2200],
                    ['name' => 'Short Can', 'purchase_price' => 1100, 'selling_price' => 1500],
                ];
                $units = collect($beerFormats)->flatMap(fn (array $format): array => [
                    ['name' => $format['name'].' Package', 'conversion' => 24, 'purchase_price' => $format['purchase_price'] * 24, 'selling_price' => $format['selling_price'] * 24, 'package_price' => $format['selling_price'] * 24, 'single_unit_price' => $format['selling_price']],
                ])->all();
            } elseif ($isSoftDrink) {
                $units = [
                    ['name' => 'Package', 'conversion' => 24, 'purchase_price' => 12000, 'selling_price' => 12000, 'package_price' => 12000, 'single_unit_price' => 500],
                ];
            } elseif ($isCigarette || $isCheroot) {
                $units = [
                    ['name' => 'Package', 'conversion' => 20, 'purchase_price' => 14000, 'selling_price' => 18000, 'package_price' => 1800, 'single_unit_price' => 100],
                    ['name' => 'Carton', 'conversion' => 200, 'purchase_price' => 14000, 'selling_price' => 18000, 'package_price' => 1800, 'single_unit_price' => 100],
                ];
            } else {
                $units = [['name' => 'Piece', 'conversion' => 1, 'selling_price' => 0, 'single_unit_price' => 0]];
            }

            $product = Product::create([
                'category_id' => $categoryMap[$productData['category_id']]->id,
                'name' => $productData['name'],
                'sku' => $productData['sku'],
                'price_mode' => $priceMode,
                'base_unit' => $baseUnit,
                'reorder_level' => 0,
                'active' => $productData['is_active'],
            ]);

            foreach ($units as $unit) {
                $createdUnit = $product->units()->create([...$unit, 'conversion' => $unit['conversion'] ?? 1, 'package_quantity' => 0, 'loose_quantity' => 0, 'quantity_base' => 0]);
                $createdUnit->stock()->create(['product_id' => $product->id]);
            }
        }
    }
}
