<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            [
                "id" => 1,
                "category_id" => 4,
                "name" => "Glan Master - အဝါ",
                "sku" => "GM-001",
                "brand" => "Glan Master",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 2,
                "category_id" => 4,
                "name" => "Glan Master - အနီ",
                "sku" => "GM-002",
                "brand" => "Glan Master",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 3,
                "category_id" => 4,
                "name" => "Glan Master - အပြာ",
                "sku" => "GM-003",
                "brand" => "Glan Master",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 4,
                "category_id" => 4,
                "name" => "Royal Club - အစိမ်း",
                "sku" => "RC-001",
                "brand" => "Royal Club",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 5,
                "category_id" => 4,
                "name" => "Royal Club - အပြာ",
                "sku" => "RC-002",
                "brand" => "Royal Club",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 6,
                "category_id" => 4,
                "name" => "Royal Club - အဝါ",
                "sku" => "RC-003",
                "brand" => "Royal Club",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 7,
                "category_id" => 4,
                "name" => "MacArthur\'s - Whiskey",
                "sku" => "MA-001",
                "brand" => "MacArthur\'s",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 8,
                "category_id" => 4,
                "name" => "Grand Royal - Double Gold",
                "sku" => "GR-001",
                "brand" => "Grand Royal",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 9,
                "category_id" => 4,
                "name" => "Grand Royal - Sherry Cask",
                "sku" => "GR-002",
                "brand" => "Grand Royal",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 10,
                "category_id" => 4,
                "name" => "Grand Royal - Shwe",
                "sku" => "GR-003",
                "brand" => "Grand Royal",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 11,
                "category_id" => 4,
                "name" => "Grand Royal - Signature Blue",
                "sku" => "GR-004",
                "brand" => "Grand Royal",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 12,
                "category_id" => 4,
                "name" => "Grand Royal - Smooth",
                "sku" => "GR-005",
                "brand" => "Grand Royal",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 13,
                "category_id" => 4,
                "name" => "Empire - Rum",
                "sku" => "EM-001",
                "brand" => "Empire",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 14,
                "category_id" => 4,
                "name" => "Grand Royal - Black",
                "sku" => "GR-006",
                "brand" => "Grand Royal",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 15,
                "category_id" => 4,
                "name" => "Brother - Smooth",
                "sku" => "BR-001",
                "brand" => "Brother",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 16,
                "category_id" => 4,
                "name" => "Mandalay - Rum Sherry",
                "sku" => "MD-001",
                "brand" => "Mandalay",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 17,
                "category_id" => 4,
                "name" => "Mandalay - 3 Year Export",
                "sku" => "MD-002",
                "brand" => "Mandalay",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 18,
                "category_id" => 4,
                "name" => "Mandalay - Coffee Rum",
                "sku" => "MD-003",
                "brand" => "Mandalay",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 19,
                "category_id" => 4,
                "name" => "Mandalay - White Rum",
                "sku" => "MD-004",
                "brand" => "Mandalay",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 20,
                "category_id" => 4,
                "name" => "Mandalay - Rum",
                "sku" => "MD-005",
                "brand" => "Mandalay",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 21,
                "category_id" => 4,
                "name" => "Mandalay - Rum Gold",
                "sku" => "MD-007",
                "brand" => "Mandalay",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 22,
                "category_id" => 4,
                "name" => "Myanmar - Rum Celebration",
                "sku" => "MY-002",
                "brand" => "Myanmar",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 23,
                "category_id" => 4,
                "name" => "Myanmar - Dry Gin",
                "sku" => "MY-003",
                "brand" => "Myanmar",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 24,
                "category_id" => 4,
                "name" => "Army - Rum",
                "sku" => "AR-001",
                "brand" => "Army",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 25,
                "category_id" => 4,
                "name" => "Dagon - Rum",
                "sku" => "DG-001",
                "brand" => "Dagon",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 26,
                "category_id" => 4,
                "name" => "Johnnie Walker - Blue Label",
                "sku" => "JW-001",
                "brand" => "Johnnie Walker",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 27,
                "category_id" => 4,
                "name" => "Johnnie Walker - Double Black",
                "sku" => "JW-002",
                "brand" => "Johnnie Walker",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 28,
                "category_id" => 4,
                "name" => "Johnnie Walker - Black Label",
                "sku" => "JW-003",
                "brand" => "Johnnie Walker",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 29,
                "category_id" => 4,
                "name" => "Johnnie Walker - Red Label",
                "sku" => "JW-004",
                "brand" => "Johnnie Walker",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 30,
                "category_id" => 4,
                "name" => "Chivas Regal - 12 Year",
                "sku" => "CR-001",
                "brand" => "Chivas Regal",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 31,
                "category_id" => 4,
                "name" => "Black Icon",
                "sku" => "BI-001",
                "brand" => "Black Icon",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 32,
                "category_id" => 4,
                "name" => "Dunfife - အပြာ",
                "sku" => "DF-001",
                "brand" => "Dunfife",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 33,
                "category_id" => 4,
                "name" => "Dunfife - အနီ",
                "sku" => "DF-002",
                "brand" => "Dunfife",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 34,
                "category_id" => 4,
                "name" => "Jägermeister",
                "sku" => "JM-001",
                "brand" => "Jägermeister",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 35,
                "category_id" => 4,
                "name" => "ခေါင်ရည်ဘုရင် ၂ဆ",
                "sku" => "KH-001",
                "brand" => "",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 36,
                "category_id" => 4,
                "name" => "ကိုးတောင်ကျား",
                "sku" => "KT-001",
                "brand" => "",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 37,
                "category_id" => 4,
                "name" => "စစ်မြင်း",
                "sku" => "SM-003",
                "brand" => "",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 38,
                "category_id" => 3,
                "name" => "Sir Edward\'s - Smoky",
                "sku" => "SE-001",
                "brand" => "Sir Edward\'s",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 39,
                "category_id" => 3,
                "name" => "Sir Edward\'s - Finest",
                "sku" => "SE-002",
                "brand" => "Sir Edward\'s",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 40,
                "category_id" => 3,
                "name" => "Sir Edward\'s - Beer Reserve",
                "sku" => "SE-003",
                "brand" => "Sir Edward\'s",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 41,
                "category_id" => 3,
                "name" => "Keen - Beer",
                "sku" => "KN-001",
                "brand" => "Keen",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 42,
                "category_id" => 3,
                "name" => "Myanmar - Beer",
                "sku" => "MY-001",
                "brand" => "Myanmar",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 43,
                "category_id" => 3,
                "name" => "Black Shield - Beer",
                "sku" => "BS-001",
                "brand" => "Black Shield",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 44,
                "category_id" => 3,
                "name" => "Andaman Gold - Beer",
                "sku" => "AG-001",
                "brand" => "Andaman Gold",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 45,
                "category_id" => 3,
                "name" => "Chang - Beer",
                "sku" => "CH-001",
                "brand" => "Chang",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 46,
                "category_id" => 3,
                "name" => "Dagon - Beer",
                "sku" => "DG-002",
                "brand" => "Dagon",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 47,
                "category_id" => 3,
                "name" => "Army - Beer",
                "sku" => "AR-002",
                "brand" => "Army",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 48,
                "category_id" => 3,
                "name" => "Tuborg - Beer",
                "sku" => "TB-001",
                "brand" => "Tuborg",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 49,
                "category_id" => 3,
                "name" => "Carlsberg - Beer",
                "sku" => "CB-001",
                "brand" => "Carlsberg",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 50,
                "category_id" => 3,
                "name" => "Yoma - Beer",
                "sku" => "YM-001",
                "brand" => "Yoma",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 51,
                "category_id" => 3,
                "name" => "Black Eagle - Beer",
                "sku" => "BE-001",
                "brand" => "Black Eagle",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 52,
                "category_id" => 3,
                "name" => "Tapper - Beer",
                "sku" => "TP-001",
                "brand" => "Tapper",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 53,
                "category_id" => 3,
                "name" => "Dagon - Super Beer",
                "sku" => "DG-003",
                "brand" => "Dagon",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 54,
                "category_id" => 3,
                "name" => "Yagon - Beer",
                "sku" => "YG-001",
                "brand" => "Yagon",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 55,
                "category_id" => 3,
                "name" => "Mandalay - Beer",
                "sku" => "MD-006",
                "brand" => "Mandalay",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 56,
                "category_id" => 3,
                "name" => "Budweiser - Beer",
                "sku" => "BW-001",
                "brand" => "Budweiser",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 57,
                "category_id" => 3,
                "name" => "Corona - Beer",
                "sku" => "CO-001",
                "brand" => "Corona",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 58,
                "category_id" => 3,
                "name" => "Singha - Beer",
                "sku" => "SG-001",
                "brand" => "Singha",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 59,
                "category_id" => 3,
                "name" => "Leo - Beer",
                "sku" => "LO-001",
                "brand" => "Leo",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 60,
                "category_id" => 3,
                "name" => "Heineken - Beer",
                "sku" => "HN-001",
                "brand" => "Heineken",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 61,
                "category_id" => 3,
                "name" => "ABC - Beer",
                "sku" => "AB-001",
                "brand" => "ABC",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 62,
                "category_id" => 3,
                "name" => "Tiger - Beer",
                "sku" => "TG-001",
                "brand" => "Tiger",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 63,
                "category_id" => 3,
                "name" => "Tiger - Crystal",
                "sku" => "TG-002",
                "brand" => "Tiger",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 64,
                "category_id" => 3,
                "name" => "Tiger - Super",
                "sku" => "TG-003",
                "brand" => "Tiger",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 65,
                "category_id" => 3,
                "name" => "Tiger - Soju",
                "sku" => "TG-004",
                "brand" => "Tiger",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 66,
                "category_id" => 3,
                "name" => "Bavaria - Beer",
                "sku" => "BV-001",
                "brand" => "Bavaria",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 67,
                "category_id" => 3,
                "name" => "R7 - အပြာ",
                "sku" => "R7-001",
                "brand" => "R7",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 68,
                "category_id" => 3,
                "name" => "R7 - အနီ",
                "sku" => "R7-002",
                "brand" => "R7",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 69,
                "category_id" => 3,
                "name" => "Bawdar - Beer",
                "sku" => "BW-002",
                "brand" => "Bawdar",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 70,
                "category_id" => 6,
                "name" => "Bora - Soju",
                "sku" => "BO-001",
                "brand" => "Bora",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 71,
                "category_id" => 6,
                "name" => "Joei - Soju",
                "sku" => "JE-001",
                "brand" => "Joei",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 72,
                "category_id" => 6,
                "name" => "Geonbae - Soju",
                "sku" => "GB-001",
                "brand" => "Geonbae",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 73,
                "category_id" => 6,
                "name" => "Chingu - Soju",
                "sku" => "CG-001",
                "brand" => "Chingu",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 74,
                "category_id" => 7,
                "name" => "Fullmoon - Wine",
                "sku" => "FM-001",
                "brand" => "Fullmoon",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 75,
                "category_id" => 7,
                "name" => "MayMyoWine - Wine",
                "sku" => "MW-001",
                "brand" => "MayMyoWine",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 76,
                "category_id" => 5,
                "name" => "A1 - Drink",
                "sku" => "A1-001",
                "brand" => "A1",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 77,
                "category_id" => 5,
                "name" => "Blink - Energy Drink",
                "sku" => "BL-001",
                "brand" => "Blink",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 78,
                "category_id" => 5,
                "name" => "RRB - Energy Drink",
                "sku" => "RRB-001",
                "brand" => "RRB",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 79,
                "category_id" => 5,
                "name" => "Pop - Soda",
                "sku" => "PP-001",
                "brand" => "Pop",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 80,
                "category_id" => 5,
                "name" => "Dagon - Soda",
                "sku" => "DG-004",
                "brand" => "Dagon",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 81,
                "category_id" => 5,
                "name" => "Vitamilk - Soy Milk",
                "sku" => "VM-001",
                "brand" => "Vitamilk",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 82,
                "category_id" => 5,
                "name" => "Enervit - Energy Drink",
                "sku" => "EV-001",
                "brand" => "Enervit",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 83,
                "category_id" => 5,
                "name" => "Color - Cola",
                "sku" => "CL-001",
                "brand" => "Color",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 84,
                "category_id" => 5,
                "name" => "Honey Gold - Drink",
                "sku" => "HG-001",
                "brand" => "Honey Gold",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 85,
                "category_id" => 5,
                "name" => "Sunkist - Soft Drink",
                "sku" => "SK-001",
                "brand" => "Sunkist",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 86,
                "category_id" => 5,
                "name" => "Mirinda - Soft Drink",
                "sku" => "MR-001",
                "brand" => "Mirinda",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 87,
                "category_id" => 5,
                "name" => "M-150 - Energy Drink",
                "sku" => "M1-001",
                "brand" => "M-150",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 88,
                "category_id" => 5,
                "name" => "Carabao - Energy Drink",
                "sku" => "CRB-001",
                "brand" => "Carabao",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 89,
                "category_id" => 5,
                "name" => "Fire Dragon - Energy Drink",
                "sku" => "FD-001",
                "brand" => "Fire Dragon",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 90,
                "category_id" => 5,
                "name" => "Speed - Energy Drink",
                "sku" => "SP-001",
                "brand" => "Speed",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 91,
                "category_id" => 5,
                "name" => "Lipo - Energy Drink",
                "sku" => "LP-001",
                "brand" => "Lipo",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 92,
                "category_id" => 5,
                "name" => "C-Vitt - Vitamin Drink",
                "sku" => "CV-001",
                "brand" => "C-Vitt",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 93,
                "category_id" => 5,
                "name" => "Shark - Energy Drink",
                "sku" => "SH-001",
                "brand" => "Shark",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 94,
                "category_id" => 5,
                "name" => "Lucky Day - Coffee",
                "sku" => "LD-001",
                "brand" => "Lucky Day",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 95,
                "category_id" => 5,
                "name" => "UFC - Drink",
                "sku" => "UF-001",
                "brand" => "UFC",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 96,
                "category_id" => 5,
                "name" => "Sunday - Drink",
                "sku" => "SD-001",
                "brand" => "Sunday",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 97,
                "category_id" => 5,
                "name" => "Lactasoy - Soy Milk",
                "sku" => "LS-001",
                "brand" => "Lactasoy",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 98,
                "category_id" => 5,
                "name" => "Milo - Chocolate Malt",
                "sku" => "ML-001",
                "brand" => "Milo",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 99,
                "category_id" => 5,
                "name" => "Ovaltine - Chocolate Malt",
                "sku" => "OV-001",
                "brand" => "Ovaltine",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 100,
                "category_id" => 5,
                "name" => "Vita - Drink",
                "sku" => "VT-001",
                "brand" => "Vita",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 101,
                "category_id" => 5,
                "name" => "Yoko - Drink",
                "sku" => "YK-001",
                "brand" => "Yoko",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 102,
                "category_id" => 5,
                "name" => "Max Plus - Drink",
                "sku" => "MX-001",
                "brand" => "Max Plus",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 103,
                "category_id" => 5,
                "name" => "V Cola - Cola",
                "sku" => "VC-001",
                "brand" => "V Cola",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 104,
                "category_id" => 5,
                "name" => "D-POP - Drink",
                "sku" => "DP-001",
                "brand" => "D-POP",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 105,
                "category_id" => 5,
                "name" => "Alpine - Drink",
                "sku" => "AL-001",
                "brand" => "Alpine",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 106,
                "category_id" => 5,
                "name" => "Hikari - Drink",
                "sku" => "HK-001",
                "brand" => "Hikari",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 107,
                "category_id" => 5,
                "name" => "Royal-D - Drink",
                "sku" => "RD-001",
                "brand" => "Royal-D",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 108,
                "category_id" => 5,
                "name" => "Regen-D - Drink",
                "sku" => "RG-001",
                "brand" => "Regen-D",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 109,
                "category_id" => 5,
                "name" => "Pepsi - Cola",
                "sku" => "PE-001",
                "brand" => "Pepsi",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 110,
                "category_id" => 5,
                "name" => "Sting - Energy Drink",
                "sku" => "ST-001",
                "brand" => "Sting",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 111,
                "category_id" => 5,
                "name" => "Blue Mountain - Drink",
                "sku" => "BM-001",
                "brand" => "Blue Mountain",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 112,
                "category_id" => 5,
                "name" => "Asia Delight - Drink",
                "sku" => "AD-001",
                "brand" => "Asia Delight",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 113,
                "category_id" => 5,
                "name" => "Asia - ပင်မည့်",
                "sku" => "AS-001",
                "brand" => "Asia",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 114,
                "category_id" => 5,
                "name" => "Asia - လိုင်ချီး",
                "sku" => "AS-002",
                "brand" => "Asia",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 115,
                "category_id" => 5,
                "name" => "Yoshi - Drink",
                "sku" => "YS-001",
                "brand" => "Yoshi",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 116,
                "category_id" => 5,
                "name" => "သူဌေးမင်း",
                "sku" => "STM-001",
                "brand" => "",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 117,
                "category_id" => 5,
                "name" => "Hello အရေခဲချောင်း",
                "sku" => "HE-001",
                "brand" => "",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 118,
                "category_id" => 5,
                "name" => "ဝါးဟားဟား",
                "sku" => "WH-001",
                "brand" => "",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 119,
                "category_id" => 5,
                "name" => "မန်းရှယ်",
                "sku" => "MS-001",
                "brand" => "",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 120,
                "category_id" => 5,
                "name" => "မန်းမန်ကျည်း",
                "sku" => "MM-001",
                "brand" => "",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 121,
                "category_id" => 5,
                "name" => "ဂျော်ကီ",
                "sku" => "JK-001",
                "brand" => "",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 122,
                "category_id" => 5,
                "name" => "ဇေ",
                "sku" => "ZE-001",
                "brand" => "",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 123,
                "category_id" => 5,
                "name" => "Sandar Aung - Drink",
                "sku" => "SA-001",
                "brand" => "Sandar Aung",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 124,
                "category_id" => 8,
                "name" => "Jasper - Water",
                "sku" => "JP-001",
                "brand" => "Jasper",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 125,
                "category_id" => 8,
                "name" => "Life - Water",
                "sku" => "LF-001",
                "brand" => "Life",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 126,
                "category_id" => 10,
                "name" => "My Chip - Chips",
                "sku" => "MC-001",
                "brand" => "My Chip",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 127,
                "category_id" => 10,
                "name" => "Oshi - Snack",
                "sku" => "OS-001",
                "brand" => "Oshi",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 128,
                "category_id" => 10,
                "name" => "3+2 - Biscuit",
                "sku" => "TK-001",
                "brand" => "3+2",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 129,
                "category_id" => 10,
                "name" => "၂၀၀ တန်",
                "sku" => "PT-001",
                "brand" => "",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 130,
                "category_id" => 10,
                "name" => "၃၀၀ တန်",
                "sku" => "PT-002",
                "brand" => "",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 131,
                "category_id" => 10,
                "name" => "၆၀၀ တန်",
                "sku" => "PT-003",
                "brand" => "",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 132,
                "category_id" => 10,
                "name" => "၇၀၀ တန်",
                "sku" => "PT-004",
                "brand" => "",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 133,
                "category_id" => 10,
                "name" => "၈၀၀ တန်",
                "sku" => "PT-005",
                "brand" => "",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 134,
                "category_id" => 10,
                "name" => "၁၀၀၀ တန်",
                "sku" => "PT-006",
                "brand" => null,
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 08:12:07",
            ],
            [
                "id" => 135,
                "category_id" => 10,
                "name" => "၁၂၀၀ တန်",
                "sku" => "PT-007",
                "brand" => "",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 136,
                "category_id" => 10,
                "name" => "၁၅၀၀ တန်",
                "sku" => "PT-008",
                "brand" => "",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 137,
                "category_id" => 9,
                "name" => "ယိုးဒယား မျက်လုံး",
                "sku" => "ND-001",
                "brand" => "",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 138,
                "category_id" => 9,
                "name" => "Jumbo - Noodle",
                "sku" => "JB-001",
                "brand" => "Jumbo",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 139,
                "category_id" => 9,
                "name" => "X-cite - Noodle",
                "sku" => "XC-001",
                "brand" => "X-cite",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 140,
                "category_id" => 9,
                "name" => "OMG - Noodle",
                "sku" => "OG-001",
                "brand" => "OMG",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 141,
                "category_id" => 9,
                "name" => "MAMA - Noodle",
                "sku" => "MZ-001",
                "brand" => "MAMA",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 142,
                "category_id" => 9,
                "name" => "Yum Yum - Noodle",
                "sku" => "YY-001",
                "brand" => "Yum Yum",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 143,
                "category_id" => 9,
                "name" => "XOXO - Noodle",
                "sku" => "XX-001",
                "brand" => "XOXO",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 144,
                "category_id" => 9,
                "name" => "ယိုးဒယား ကြာဇံ",
                "sku" => "ND-002",
                "brand" => "",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 145,
                "category_id" => 9,
                "name" => "Shin Shin - ကြာဇံ",
                "sku" => "SS-001",
                "brand" => "Shin Shin",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 146,
                "category_id" => 9,
                "name" => "Ultra - Volcano",
                "sku" => "UV-001",
                "brand" => "Ultra",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 147,
                "category_id" => 2,
                "name" => "Mevius - Sky Blue",
                "sku" => "MV-001",
                "brand" => "Mevius",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 148,
                "category_id" => 2,
                "name" => "Winston - Cigarettes",
                "sku" => "WS-001",
                "brand" => "Winston",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 149,
                "category_id" => 2,
                "name" => "Lord - Cigarettes",
                "sku" => "LR-001",
                "brand" => "Lord",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 150,
                "category_id" => 2,
                "name" => "Dunhill - Red",
                "sku" => "DH-001",
                "brand" => "Dunhill",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 151,
                "category_id" => 2,
                "name" => "Black Devil - Cigarettes",
                "sku" => "BD-001",
                "brand" => "Black Devil",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 152,
                "category_id" => 2,
                "name" => "Black Fox - Cigarettes",
                "sku" => "BF-001",
                "brand" => "Black Fox",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 153,
                "category_id" => 2,
                "name" => "Red Ruby - Cigarettes",
                "sku" => "RU-001",
                "brand" => "Red Ruby",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 154,
                "category_id" => 2,
                "name" => "Premium Gold - Cigarettes",
                "sku" => "PG-001",
                "brand" => "Premium Gold",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 155,
                "category_id" => 2,
                "name" => "Red and Blue - Cigarettes",
                "sku" => "RB-001",
                "brand" => "Red and Blue",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 156,
                "category_id" => 2,
                "name" => "Oris - Cigarettes",
                "sku" => "OR-001",
                "brand" => "Oris",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 157,
                "category_id" => 2,
                "name" => "Capital - Cigarettes",
                "sku" => "CP-001",
                "brand" => "Capital",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 158,
                "category_id" => 2,
                "name" => "O3 - Cigarettes",
                "sku" => "O3-001",
                "brand" => "O3",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 159,
                "category_id" => 2,
                "name" => "Napoli - Cigarettes",
                "sku" => "NP-001",
                "brand" => "Napoli",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 160,
                "category_id" => 1,
                "name" => "ကြယ်နီ",
                "sku" => "KS-001",
                "brand" => "",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 161,
                "category_id" => 1,
                "name" => "လွင့်",
                "sku" => "LW-001",
                "brand" => "",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 162,
                "category_id" => 1,
                "name" => "ရွှေဘားမား",
                "sku" => "SM-001",
                "brand" => "",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 163,
                "category_id" => 1,
                "name" => "စကားဝါ",
                "sku" => "SC-001",
                "brand" => "",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 164,
                "category_id" => 1,
                "name" => "မယ်ခွေ Strong",
                "sku" => "MK-001",
                "brand" => "",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 165,
                "category_id" => 1,
                "name" => "မယ်ခွေ Smooth",
                "sku" => "MK-002",
                "brand" => "",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 166,
                "category_id" => 1,
                "name" => "ရွှေမန်းသူ",
                "sku" => "SM-002",
                "brand" => "",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 167,
                "category_id" => 11,
                "name" => "Tissue",
                "sku" => "TS-001",
                "brand" => "",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 07:50:38",
                "updated_at" => "2026-08-14 07:50:38",
            ],
            [
                "id" => 168,
                "category_id" => 10,
                "name" => "လေးကျော်",
                "sku" => "-0168",
                "brand" => "လေးကျော်",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 08:14:40",
                "updated_at" => "2026-08-14 08:14:40",
            ],
            [
                "id" => 169,
                "category_id" => 10,
                "name" => "အပျိုကြီး",
                "sku" => "-0169",
                "brand" => "အပျိုကြီး",
                "is_active" => true,
                "deleted_at" => null,
                "created_at" => "2026-08-14 08:16:14",
                "updated_at" => "2026-08-14 08:16:14",
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
