services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    working_dir: /var/www
    ports:
      - "8000:8000"
    volumes:
      - ./:/var/www
      - ./storage:/var/www/storage
    environment:
      APP_URL: ${APP_URL:-http://localhost}
      DB_CONNECTION: ${DB_CONNECTION:-mysql}
      DB_HOST: ${DB_HOST:-mysql}
      DB_PORT: ${DB_PORT:-3306}
      DB_DATABASE: ${DB_DATABASE:-minipos}
      DB_USERNAME: ${DB_USERNAME:-root}
      DB_PASSWORD: ${DB_PASSWORD:-asdffdsa}
      REDIS_CLIENT: phpredis
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - laravel-net
    depends_on:
      - mysql
      - redis

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - laravel-net

  mysql:
    image: jsurf/rpi-mariadb:latest
    container_name: mysql
    restart: unless-stopped
    ports:
      - "${DB_PORT:-3306}:3306"
    environment:
      TZ: "Asia/Yangon"
      MYSQL_DATABASE: ${DB_DATABASE:-minipos}
      MYSQL_PASSWORD: ${DB_PASSWORD:-asdffdsa}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-asdffdsa}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel-net
    command: --innodb_use_native_aio=0

networks:
  laravel-net:
    driver: bridge

volumes:
  db_data:
  redis_data:
