export { login, logout, home, dashboard } from './routes/index'
export { index as categories, store as categoriesStore, update as categoriesUpdate, destroy as categoriesDestroy, toggleActive as categoriesToggleActive, restore as categoriesRestore } from './routes/categories'
export { index as units, store as unitsStore, update as unitsUpdate, destroy as unitsDestroy } from './routes/units'
export { index as products, create as productsCreate, store as productsStore, show as productsShow, edit as productsEdit, update as productsUpdate, destroy as productsDestroy, toggleActive as productsToggleActive, restore as productsRestore } from './routes/products'
export { index as inventory, create as inventoryCreate, store as inventoryStore, searchProducts as inventorySearchProducts } from './routes/inventory'
export { profitLoss as reportsProfitLoss } from './routes/reports'
export { store as variantsStore, update as variantsUpdate, destroy as variantsDestroy } from './routes/variants'
