export { login, logout, home, dashboard } from './routes/index'
export { index as categories, store as categoriesStore, update as categoriesUpdate, destroy as categoriesDestroy, toggleActive as categoriesToggleActive, restore as categoriesRestore } from './routes/categories'
export { index as units, store as unitsStore, update as unitsUpdate, destroy as unitsDestroy } from './routes/units'
export { index as products, create as productsCreate, store as productsStore, show as productsShow, edit as productsEdit, update as productsUpdate, destroy as productsDestroy, toggleActive as productsToggleActive, restore as productsRestore, stockPriceUpdate as productsStockPriceUpdate } from './routes/products'
export { index as sales, checkoutPage as salesCheckoutPage, checkout as salesCheckout, addItems as salesAddItems } from './routes/sales'
export { store as variantsStore, update as variantsUpdate, destroy as variantsDestroy, updateStockPrice as variantsUpdateStockPrice } from './routes/variants'
