<script setup lang="ts">
import { Head, Link, router, useForm } from '@inertiajs/vue3';
import { computed, ref } from 'vue';
import { ArrowLeft, ArrowRight, BarChart3, ClipboardList, FileText, Package, Plus, Search, Trash2, TrendingUp, Truck } from '@lucide/vue';
import FormActions from '@/components/forms/FormActions.vue';
import FormField from '@/components/forms/FormField.vue';
import FormSection from '@/components/forms/FormSection.vue';
import { dashboard } from '@/routes';
import { index as categoryIndex, store as categoryStore, update as categoryUpdate, destroy as categoryDestroy } from '@/routes/categories';
import { index as supplierIndex, store as supplierStore, update as supplierUpdate, destroy as supplierDestroy } from '@/routes/suppliers';
import { index as purchaseIndex, create as purchaseCreate, store as purchaseStore, show as purchaseShow } from '@/routes/purchases';
import { show as saleShow, cancel as saleCancel } from '@/routes/sales';
import { index as inventoryIndex } from '@/routes/inventory';
import { index as adjustmentIndex, create as adjustmentCreate, store as adjustmentStore, show as adjustmentShow } from '@/routes/adjustments';
import { index as reportIndex } from '@/routes/reports';

type Page<T> = { data: T[]; from?: number; to?: number; total?: number; current_page?: number; last_page?: number };
type Unit = { id: number; name: string; conversion: number; selling_price?: number; purchase_price?: number };
type Product = { id: number; name: string; sku?: string; base_unit?: string; reorder_level?: number; category?: { name: string }; units: Unit[]; stock?: { quantity_base: number } | null };
type RecordItem = { id: number; name: string; description?: string; contact_name?: string; email?: string; phone?: string; address?: string; active?: boolean; products_count?: number };
type TransactionItem = { id: number; product?: Product; unit?: Unit; quantity: number; unit_cost?: number; unit_price?: number; total?: number };
type Purchase = { id: number; invoice_number: string; purchased_at: string; supplier?: { name: string } | null; user?: { name: string }; subtotal: number; total: number; notes?: string; items?: TransactionItem[] };
type Sale = { id: number; invoice_number: string; sold_at: string; payment_method: string; subtotal: number; discount: number; tax: number; total: number; received_amount: number; change_amount?: number; cancelled_at?: string | null; user?: { name: string }; items?: TransactionItem[] };
type Adjustment = { id: number; adjustment_type: string; quantity: number; quantity_base: number; unit_conversion: number; reason: string; notes?: string; adjusted_at: string; product?: Product; user?: { name: string } };

const props = defineProps<{ section: string; title: string; description: string; categories?: Page<RecordItem>; suppliers?: any; products?: any; purchases?: Page<Purchase>; purchase?: Purchase; sales?: Page<Sale>; sale?: Sale; adjustments?: Page<Adjustment>; adjustment?: Adjustment; summary?: Record<string, number>; filters?: { from: string; to: string } }>();
const money = (value = 0) => `${new Intl.NumberFormat('en-US').format(Number(value))} MMK`;
const date = (value?: string) => value ? new Intl.DateTimeFormat('en-US', { dateStyle: 'medium' }).format(new Date(value)) : '—';
const products = computed(() => Array.isArray(props.products) ? props.products : props.products?.data ?? []);
const supplierOptions = computed(() => Array.isArray(props.suppliers) ? props.suppliers : props.suppliers?.data ?? []);
const view = computed(() => { if (props.purchase) return 'purchases-show'; if (props.sale) return 'sales-show'; if (props.adjustment) return 'adjustments-show'; if (props.section === 'purchases' && Array.isArray(props.products)) return 'purchases-create'; if (props.section === 'adjustments' && Array.isArray(props.products)) return 'adjustments-create'; return props.section; });
const section = view;
const query = ref('');
const filteredProducts = computed(() => products.value.filter((product: Product) => `${product.name} ${product.sku ?? ''}`.toLowerCase().includes(query.value.toLowerCase())));

const recordForm = useForm({ name: '', description: '', contact_name: '', email: '', phone: '', address: '' });
const editingId = ref<number | null>(null);
function resetRecord(): void { editingId.value = null; recordForm.reset(); recordForm.clearErrors(); }
function editRecord(item: RecordItem): void { editingId.value = item.id; recordForm.name = item.name; recordForm.description = item.description ?? ''; recordForm.contact_name = item.contact_name ?? ''; recordForm.email = item.email ?? ''; recordForm.phone = item.phone ?? ''; recordForm.address = item.address ?? ''; }
function submitRecord(): void { const action = props.section === 'categories' ? (editingId.value ? categoryUpdate(editingId.value) : categoryStore()) : (editingId.value ? supplierUpdate(editingId.value) : supplierStore()); recordForm.submit(action, { onSuccess: resetRecord }); }
function deleteRecord(id: number): void { router.delete(props.section === 'categories' ? categoryDestroy(id) : supplierDestroy(id)); }

type PurchaseRow = { product_id: number | ''; product_unit_id: number | ''; quantity: number; unit_cost: number };
const purchaseForm = useForm({ supplier_id: '' as number | '', invoice_number: '', purchased_at: new Date().toISOString().slice(0, 10), notes: '', items: [{ product_id: '', product_unit_id: '', quantity: 1, unit_cost: 0 }] as PurchaseRow[] });
function addPurchaseRow(): void { purchaseForm.items.push({ product_id: '', product_unit_id: '', quantity: 1, unit_cost: 0 }); }
function removePurchaseRow(index: number): void { if (purchaseForm.items.length > 1) purchaseForm.items.splice(index, 1); }
function unitsFor(productId: number | ''): Unit[] { return products.value.find((product: Product) => product.id === Number(productId))?.units ?? []; }
function submitPurchase(): void { purchaseForm.submit(purchaseStore(), { onSuccess: () => purchaseForm.reset() }); }
const purchaseTotal = computed(() => purchaseForm.items.reduce((total, item) => total + Number(item.quantity) * Number(item.unit_cost), 0));
const adjustmentForm = useForm({ product_id: '' as number | '', adjustment_type: 'increase', quantity: 1, unit_conversion: 1, reason: '', notes: '' });
function submitAdjustment(): void { adjustmentForm.submit(adjustmentStore()); }
const cancelForm = useForm({ reason: '' });
function cancelSale(): void { if (props.sale) cancelForm.submit(saleCancel(props.sale.id)); }
const reportFrom = ref(props.filters?.from ?? '');
const reportTo = ref(props.filters?.to ?? '');
function filterReport(): void { router.visit(reportIndex({ query: { from: reportFrom.value, to: reportTo.value } })); }
function listRange<T>(page?: Page<T>): string { return page?.total ? `Showing ${page.from ?? 1}–${page.to ?? page.data.length} of ${page.total}` : 'No records yet'; }
function statusClass(value: string): string { return value === 'cancelled' || value === 'decrease' ? 'bg-rose-50 text-rose-600' : value === 'count' ? 'bg-amber-50 text-amber-600' : 'bg-emerald-50 text-emerald-600'; }
</script>

<template>
    <Head :title="title" />
    <div class="min-h-screen bg-[#f5f7fb] px-4 py-6 text-slate-900 dark:bg-slate-950 dark:text-slate-100 sm:px-6 lg:px-8">
        <div class="mx-auto max-w-[1500px] space-y-6">
            <header class="flex flex-col justify-between gap-4 sm:flex-row sm:items-end">
                <div class="flex items-start gap-3">
                    <Link v-if="['purchases-create', 'adjustments-create'].includes(section)" :href="section === 'purchases-create' ? purchaseIndex() : adjustmentIndex()" class="mt-1 rounded-xl border border-slate-200 bg-white p-2 text-slate-500"><ArrowLeft class="size-4" /></Link>
                    <div><p class="text-sm font-medium text-slate-400">Store operations</p><h1 class="mt-1 text-2xl font-bold tracking-tight">{{ title }}</h1><p class="mt-2 max-w-2xl text-sm text-slate-500">{{ description }}</p></div>
                </div>
                <div class="flex flex-wrap gap-2"><Link v-if="section === 'purchases'" :href="purchaseCreate()" class="action-primary"><Plus class="size-4" /> New purchase</Link><Link v-if="section === 'adjustments'" :href="adjustmentCreate()" class="action-primary"><Plus class="size-4" /> New adjustment</Link><Link v-if="section === 'sales'" :href="dashboard()" class="action-secondary">Dashboard</Link></div>
            </header>

            <FormSection v-if="section === 'categories' || section === 'suppliers'" :title="section === 'categories' ? 'Product categories' : 'Supplier directory'" :description="section === 'categories' ? 'Keep your catalog easy to browse.' : 'Manage the people and companies you buy from.'">
                <div v-if="editingId" class="mb-4 flex justify-end"><button type="button" @click="resetRecord" class="action-secondary">Cancel edit</button></div>
                <form @submit.prevent="submitRecord" class="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
                    <FormField label="Name" required :error="recordForm.errors.name"><input v-model="recordForm.name" required autocomplete="off" /></FormField>
                    <FormField v-if="section === 'categories'" label="Description" hint="Optional"><input v-model="recordForm.description" /></FormField>
                    <template v-else><FormField label="Contact name" hint="Optional"><input v-model="recordForm.contact_name" /></FormField><FormField label="Phone" hint="Optional"><input v-model="recordForm.phone" type="tel" /></FormField><FormField label="Email" hint="Optional"><input v-model="recordForm.email" type="email" autocomplete="email" /></FormField></template>
                    <FormActions :label="editingId ? 'Save changes' : 'Add record'" :processing="recordForm.processing" />
                </form>
                <p v-if="recordForm.errors.description || recordForm.errors.contact_name || recordForm.errors.email || recordForm.errors.phone" class="error mt-3" role="alert">{{ recordForm.errors.description ?? recordForm.errors.contact_name ?? recordForm.errors.email ?? recordForm.errors.phone }}</p>
                <div class="table-wrap"><table><thead><tr><th>Name</th><th>Details</th><th>Status</th><th /></tr></thead><tbody><tr v-for="item in (section === 'categories' ? categories?.data : suppliers?.data)" :key="item.id"><td class="font-semibold">{{ item.name }}</td><td class="text-slate-500">{{ section === 'categories' ? `${item.products_count ?? 0} products` : item.phone || item.email || 'No contact details' }}</td><td><span :class="item.active === false ? 'bg-slate-100 text-slate-500' : 'bg-emerald-50 text-emerald-600'" class="status">{{ item.active === false ? 'Archived' : 'Active' }}</span></td><td class="text-right"><button @click="editRecord(item)" class="table-link">Edit</button><button @click="deleteRecord(item.id)" class="table-link text-rose-500">{{ section === 'suppliers' ? 'Archive' : 'Delete' }}</button></td></tr><tr v-if="!(section === 'categories' ? categories?.data.length : suppliers?.data.length)"><td colspan="4" class="empty">No records yet.</td></tr></tbody></table></div>
            </FormSection>

            <section v-else-if="section === 'purchases'" class="panel"><div class="toolbar"><div><h2 class="font-bold">Purchase orders</h2><p class="mt-1 text-sm text-slate-400">{{ listRange(purchases) }}</p></div><Search class="size-4 text-slate-400" /></div><div class="table-wrap"><table><thead><tr><th>Invoice</th><th>Supplier</th><th>Purchased</th><th>Total</th><th>Recorded by</th><th /></tr></thead><tbody><tr v-for="item in purchases?.data" :key="item.id"><td><Link :href="purchaseShow(item.id)" class="font-semibold text-blue-600">{{ item.invoice_number }}</Link></td><td>{{ item.supplier?.name ?? 'Direct purchase' }}</td><td class="text-slate-500">{{ date(item.purchased_at) }}</td><td class="font-semibold">{{ money(item.total) }}</td><td class="text-slate-500">{{ item.user?.name ?? '—' }}</td><td class="text-right"><Link :href="purchaseShow(item.id)" class="table-link">View</Link></td></tr><tr v-if="!purchases?.data.length"><td colspan="6" class="empty">No purchases recorded.</td></tr></tbody></table></div></section>

            <FormSection v-else-if="section === 'purchases-create'" title="Create purchase" description="Record the products and costs received from a supplier."><form @submit.prevent="submitPurchase" class="space-y-5"><div class="grid gap-4 sm:grid-cols-2"><FormField label="Invoice number" required :error="purchaseForm.errors.invoice_number"><input v-model="purchaseForm.invoice_number" required /></FormField><FormField label="Purchased date" required :error="purchaseForm.errors.purchased_at"><input v-model="purchaseForm.purchased_at" required type="date" /></FormField><FormField label="Supplier" hint="Optional"><select v-model="purchaseForm.supplier_id"><option value="">Direct purchase</option><option v-for="supplier in supplierOptions" :key="supplier.id" :value="supplier.id">{{ supplier.name }}</option></select></FormField><FormField label="Notes" hint="Optional"><textarea v-model="purchaseForm.notes" rows="2" /></FormField></div><div class="flex items-center justify-between"><div><h2 class="font-bold">Items received</h2><p class="mt-1 text-sm text-slate-400">Select the exact selling unit for each line.</p></div><button type="button" @click="addPurchaseRow" class="action-secondary"><Plus class="size-4" /> Add item</button></div><div v-for="(item, index) in purchaseForm.items" :key="index" class="grid gap-3 rounded-xl border border-slate-100 bg-slate-50/70 p-3 sm:grid-cols-[1.5fr_1fr_100px_130px_auto]"><FormField label="Product" required :error="purchaseForm.errors[`items.${index}.product_id`]"><select v-model="item.product_id" required><option value="">Select product</option><option v-for="product in products" :key="product.id" :value="product.id">{{ product.name }} ({{ product.sku }})</option></select></FormField><FormField label="Unit" required :error="purchaseForm.errors[`items.${index}.product_unit_id`]"><select v-model="item.product_unit_id" required><option value="">Select unit</option><option v-for="unit in unitsFor(item.product_id)" :key="unit.id" :value="unit.id">{{ unit.name }} ×{{ unit.conversion }}</option></select></FormField><FormField label="Quantity" required :error="purchaseForm.errors[`items.${index}.quantity`]"><input v-model.number="item.quantity" min="1" required type="number" /></FormField><FormField label="Unit cost" required :error="purchaseForm.errors[`items.${index}.unit_cost`]"><input v-model.number="item.unit_cost" min="0" required type="number" /></FormField><button type="button" @click="removePurchaseRow(index)" :disabled="purchaseForm.items.length === 1" class="self-end rounded-lg p-2 text-rose-500 disabled:opacity-30"><Trash2 class="size-4" /></button></div><p v-if="purchaseForm.errors.items" class="error" role="alert">{{ purchaseForm.errors.items }}</p><div class="flex justify-end border-t border-slate-100 pt-4 text-sm font-bold">Total: {{ money(purchaseTotal) }}</div><FormActions label="Record purchase" :processing="purchaseForm.processing" /></form></FormSection>

            <section v-else-if="section === 'purchases-show' && purchase" class="panel"><div class="flex flex-col justify-between gap-3 border-b border-slate-100 pb-5 sm:flex-row"><div><p class="text-sm text-slate-400">{{ date(purchase.purchased_at) }} · {{ purchase.supplier?.name ?? 'Direct purchase' }}</p><h2 class="mt-1 text-lg font-bold">{{ purchase.invoice_number }}</h2></div><span class="status bg-emerald-50 text-emerald-600">Received</span></div><div class="table-wrap"><table><thead><tr><th>Product</th><th>Unit</th><th>Quantity</th><th>Unit cost</th><th class="text-right">Line total</th></tr></thead><tbody><tr v-for="item in purchase.items" :key="item.id"><td class="font-semibold">{{ item.product?.name }}</td><td>{{ item.unit?.name }}</td><td>{{ item.quantity }}</td><td>{{ money(item.unit_cost) }}</td><td class="text-right font-semibold">{{ money((item.quantity ?? 0) * (item.unit_cost ?? 0)) }}</td></tr></tbody></table></div><div class="mt-5 flex justify-end border-t border-slate-100 pt-5"><div class="text-right"><p class="text-sm text-slate-500">Total received</p><p class="text-2xl font-bold">{{ money(purchase.total) }}</p></div></div></section>

            <section v-else-if="section === 'sales'" class="panel"><div class="toolbar"><div><h2 class="font-bold">Sales history</h2><p class="mt-1 text-sm text-slate-400">{{ listRange(sales) }}</p></div><TrendingUp class="size-5 text-emerald-500" /></div><div class="table-wrap"><table><thead><tr><th>Invoice</th><th>Sold at</th><th>Payment</th><th>Total</th><th>Status</th><th /></tr></thead><tbody><tr v-for="item in sales?.data" :key="item.id"><td><Link :href="saleShow(item.id)" class="font-semibold text-blue-600">{{ item.invoice_number }}</Link></td><td class="text-slate-500">{{ date(item.sold_at) }}</td><td class="capitalize">{{ item.payment_method.replace('_', ' ') }}</td><td class="font-semibold">{{ money(item.total) }}</td><td><span :class="statusClass(item.cancelled_at ? 'cancelled' : 'completed')" class="status">{{ item.cancelled_at ? 'Cancelled' : 'Completed' }}</span></td><td class="text-right"><Link :href="saleShow(item.id)" class="table-link">View</Link></td></tr><tr v-if="!sales?.data.length"><td colspan="6" class="empty">No sales recorded.</td></tr></tbody></table></div></section>

            <section v-else-if="section === 'sales-show' && sale" class="grid items-start gap-6 xl:grid-cols-[1fr_320px]"><div class="panel"><div class="flex justify-between border-b border-slate-100 pb-5"><div><p class="text-sm text-slate-400">{{ date(sale.sold_at) }} · {{ sale.user?.name ?? 'Staff sale' }}</p><h2 class="mt-1 text-lg font-bold">{{ sale.invoice_number }}</h2></div><span :class="statusClass(sale.cancelled_at ? 'cancelled' : 'completed')" class="status">{{ sale.cancelled_at ? 'Cancelled' : 'Completed' }}</span></div><div class="table-wrap"><table><thead><tr><th>Product</th><th>Unit</th><th>Qty</th><th class="text-right">Amount</th></tr></thead><tbody><tr v-for="item in sale.items" :key="item.id"><td class="font-semibold">{{ item.product?.name }}</td><td>{{ item.unit?.name }}</td><td>{{ item.quantity }}</td><td class="text-right font-semibold">{{ money(item.total ?? (item.quantity * (item.unit_price ?? 0))) }}</td></tr></tbody></table></div></div><aside class="panel space-y-3"><div class="flex justify-between text-sm text-slate-500"><span>Subtotal</span><span>{{ money(sale.subtotal) }}</span></div><div class="flex justify-between text-sm text-slate-500"><span>Discount</span><span>{{ money(sale.discount) }}</span></div><div class="flex justify-between text-sm text-slate-500"><span>Tax</span><span>{{ money(sale.tax) }}</span></div><div class="flex justify-between border-t border-slate-100 pt-3 font-bold"><span>Total</span><span class="text-blue-600">{{ money(sale.total) }}</span></div><div class="border-t border-slate-100 pt-3 text-sm text-slate-500">{{ sale.payment_method.replace('_', ' ') }} · Received {{ money(sale.received_amount) }}</div><form v-if="!sale.cancelled_at" @submit.prevent="cancelSale" class="border-t border-slate-100 pt-4"><FormField label="Cancellation reason" required :error="cancelForm.errors.reason"><input v-model="cancelForm.reason" required placeholder="Required" /></FormField><FormActions label="Cancel sale" :processing="cancelForm.processing" /></form></aside></section>

             <section v-else-if="section === 'inventory'" class="panel"><div class="toolbar"><div><h2 class="font-bold">Stock on hand</h2><p class="mt-1 text-sm text-slate-400">{{ listRange(props.products as Page<Product>) }}</p></div><label class="flex items-center gap-2 rounded-xl bg-slate-50 px-3 text-sm text-slate-400"><Search class="size-4" /><input v-model="query" class="w-36 border-0 bg-transparent py-2 outline-none sm:w-52" placeholder="Search stock" /></label></div><div class="table-wrap"><table><thead><tr><th>Product</th><th>SKU</th><th>Category</th><th>Base unit</th><th class="text-right">Quantity</th><th>Status</th></tr></thead><tbody><tr v-for="product in filteredProducts" :key="product.id"><td class="font-semibold">{{ product.name }}</td><td class="text-slate-500">{{ product.sku ?? '—' }}</td><td>{{ product.category?.name ?? '—' }}</td><td>{{ product.base_unit ?? 'base' }}</td><td class="text-right font-bold">{{ product.stock?.quantity_base ?? 0 }}</td><td><span :class="(product.stock?.quantity_base ?? 0) === 0 ? 'bg-rose-50 text-rose-600' : (product.stock?.quantity_base ?? 0) <= (product.reorder_level ?? 0) ? 'bg-amber-50 text-amber-600' : 'bg-emerald-50 text-emerald-600'" class="status">{{ (product.stock?.quantity_base ?? 0) === 0 ? 'Out of stock' : (product.stock?.quantity_base ?? 0) <= (product.reorder_level ?? 0) ? 'Low stock' : 'Healthy' }}</span></td></tr></tbody></table></div></section>

            <section v-else-if="section === 'adjustments'" class="panel"><div class="toolbar"><div><h2 class="font-bold">Stock adjustments</h2><p class="mt-1 text-sm text-slate-400">{{ listRange(adjustments) }}</p></div><ClipboardList class="size-5 text-amber-500" /></div><div class="table-wrap"><table><thead><tr><th>Product</th><th>Type</th><th>Quantity</th><th>Reason</th><th>Adjusted at</th><th /></tr></thead><tbody><tr v-for="item in adjustments?.data" :key="item.id"><td class="font-semibold">{{ item.product?.name }}</td><td><span :class="statusClass(item.adjustment_type)" class="status capitalize">{{ item.adjustment_type }}</span></td><td>{{ item.quantity }} × {{ item.unit_conversion }}</td><td class="text-slate-500">{{ item.reason }}</td><td class="text-slate-500">{{ date(item.adjusted_at) }}</td><td class="text-right"><Link :href="adjustmentShow(item.id)" class="table-link">View</Link></td></tr><tr v-if="!adjustments?.data.length"><td colspan="6" class="empty">No adjustments recorded.</td></tr></tbody></table></div></section>

            <FormSection v-else-if="section === 'adjustments-create'" title="Create stock adjustment" description="Record a stock increase, decrease, or count correction."><form @submit.prevent="submitAdjustment" class="grid gap-4 sm:grid-cols-2"><FormField label="Product" required :error="adjustmentForm.errors.product_id" class="sm:col-span-2"><select v-model="adjustmentForm.product_id" required><option value="">Select product</option><option v-for="product in products" :key="product.id" :value="product.id">{{ product.name }} ({{ product.sku }})</option></select></FormField><FormField label="Adjustment type" required :error="adjustmentForm.errors.adjustment_type"><select v-model="adjustmentForm.adjustment_type"><option value="increase">Increase stock</option><option value="decrease">Decrease stock</option><option value="count">Set counted stock</option></select></FormField><FormField label="Quantity" required :error="adjustmentForm.errors.quantity"><input v-model.number="adjustmentForm.quantity" min="0" required type="number" /></FormField><FormField label="Unit conversion" required :error="adjustmentForm.errors.unit_conversion"><input v-model.number="adjustmentForm.unit_conversion" min="1" required type="number" /></FormField><FormField label="Reason" required :error="adjustmentForm.errors.reason"><input v-model="adjustmentForm.reason" required maxlength="100" placeholder="Damaged, count, expired…" /></FormField><FormField label="Notes" :error="adjustmentForm.errors.notes" class="sm:col-span-2"><textarea v-model="adjustmentForm.notes" rows="3" /></FormField><FormActions label="Record adjustment" :processing="adjustmentForm.processing" /></form></FormSection>

            <section v-else-if="section === 'adjustments-show' && adjustment" class="panel max-w-3xl"><div class="flex justify-between border-b border-slate-100 pb-5"><div><p class="text-sm text-slate-400">{{ date(adjustment.adjusted_at) }} · {{ adjustment.user?.name ?? 'Staff adjustment' }}</p><h2 class="mt-1 text-lg font-bold">{{ adjustment.product?.name }}</h2></div><span :class="statusClass(adjustment.adjustment_type)" class="status capitalize">{{ adjustment.adjustment_type }}</span></div><dl class="mt-5 grid gap-5 sm:grid-cols-3"><div><dt class="text-xs text-slate-400">Quantity entered</dt><dd class="mt-1 font-semibold">{{ adjustment.quantity }}</dd></div><div><dt class="text-xs text-slate-400">Unit conversion</dt><dd class="mt-1 font-semibold">{{ adjustment.unit_conversion }}</dd></div><div><dt class="text-xs text-slate-400">Base quantity changed</dt><dd class="mt-1 font-semibold">{{ adjustment.quantity_base }}</dd></div><div class="sm:col-span-3"><dt class="text-xs text-slate-400">Reason</dt><dd class="mt-1 font-semibold">{{ adjustment.reason }}</dd></div><div v-if="adjustment.notes" class="sm:col-span-3"><dt class="text-xs text-slate-400">Notes</dt><dd class="mt-1 text-sm text-slate-600">{{ adjustment.notes }}</dd></div></dl></section>

            <section v-else-if="section === 'reports'" class="space-y-6"><FormSection title="Reporting period" description="Choose a date range to refresh the operations summary."><form @submit.prevent="filterReport" class="grid gap-4 sm:grid-cols-[1fr_1fr_auto] sm:items-end"><FormField label="From"><input v-model="reportFrom" type="date" /></FormField><FormField label="To"><input v-model="reportTo" type="date" /></FormField><FormActions label="Apply filters" /></form></FormSection><div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><article v-for="stat in [{ label: 'Sales revenue', value: money(summary?.sales) }, { label: 'Transactions', value: summary?.transactions ?? 0 }, { label: 'Active products', value: summary?.products ?? 0 }, { label: 'Stock movements', value: summary?.movements ?? 0 }]" :key="stat.label" class="panel"><p class="text-sm text-slate-500">{{ stat.label }}</p><p class="mt-3 text-2xl font-bold tracking-tight">{{ stat.value }}</p><p class="mt-2 text-xs text-slate-400">Selected reporting period</p></article></div><div class="panel flex items-start gap-4"><div class="rounded-xl bg-blue-50 p-3 text-blue-600"><FileText class="size-5" /></div><div><h2 class="font-bold">Operations snapshot</h2><p class="mt-1 text-sm text-slate-500">Use the summary above to compare revenue, transactions, active catalog size and inventory activity over any date range.</p></div></div></section>

            <section v-else class="panel"><div class="flex items-center gap-4"><div class="rounded-xl bg-blue-50 p-3 text-blue-600"><Package class="size-5" /></div><div><h2 class="font-bold">Operations overview</h2><p class="mt-1 text-sm text-slate-500">Choose an operations area from the navigation to get started.</p></div></div><div class="mt-5 flex flex-wrap gap-2"><Link :href="categoryIndex()" class="action-secondary">Categories <ArrowRight class="size-4" /></Link><Link :href="supplierIndex()" class="action-secondary">Suppliers <Truck class="size-4" /></Link><Link :href="inventoryIndex()" class="action-secondary">Inventory <Package class="size-4" /></Link></div></section>
        </div>
    </div>
</template>

<style>
@reference "../../../css/app.css";
.panel { @apply rounded-2xl border border-slate-200/80 bg-white p-5 shadow-sm sm:p-6 dark:border-slate-800 dark:bg-slate-900; }
.action-primary { @apply inline-flex items-center gap-2 rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white shadow-lg shadow-blue-600/20 transition hover:bg-blue-700 disabled:cursor-not-allowed disabled:opacity-50; }
.action-secondary { @apply inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold text-slate-600 transition hover:border-blue-200 hover:bg-blue-50 hover:text-blue-600 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-300 dark:hover:bg-blue-950/40; }
[class*="space-y-1.5"] input, [class*="space-y-1.5"] select, [class*="space-y-1.5"] textarea { @apply mt-2 w-full rounded-xl border-slate-200 bg-white px-3 py-2.5 text-sm font-normal text-slate-700 outline-none transition focus:border-blue-400 focus:ring-2 focus:ring-blue-100 dark:border-slate-700 dark:bg-slate-800 dark:text-slate-100; }
.error { @apply text-sm font-medium text-rose-600; }
.toolbar { @apply flex flex-col justify-between gap-3 border-b border-slate-100 pb-5 dark:border-slate-800 sm:flex-row sm:items-center; }
.table-wrap { @apply mt-5 overflow-x-auto; }
table { @apply w-full min-w-[680px] text-left text-sm; }
th { @apply bg-slate-50 px-4 py-3 text-xs font-medium tracking-wide text-slate-400 uppercase first:rounded-l-lg last:rounded-r-lg dark:bg-slate-800; }
td { @apply border-b border-slate-100 px-4 py-4 align-middle dark:border-slate-800; }
.table-link { @apply mr-3 text-xs font-semibold text-blue-600 hover:underline; }
.status { @apply inline-flex rounded-full px-2.5 py-1 text-xs font-semibold; }
.empty { @apply py-12 text-center text-sm text-slate-400; }
</style>
